version: '3.8'

services:
  db:
    image: postgres:13
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - transcendance
    restart: always
    env_file: .env

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/mysite:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - transcendance
    restart: on-failure
    env_file: .env

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./certs:/etc/nginx/certs
    ports:
      - "9443:9443"
    depends_on:
      - backend
    networks:
      - transcendance
    restart: on-failure

volumes:
 db_data:
    driver: local

networks:
  transcendance:
    name: transcendance